# Generated by Django 4.2.6 on 2023-10-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_payment_course_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_course_lesson',
            field=models.CharField(choices=[('курс', 'курс'), ('урок ', 'урок')], max_length=50, verbose_name='платеж'),
        ),
    ]
