# Generated by Django 4.2.6 on 2023-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payments_payment_course_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='card',
            field=models.CharField(default='0000000000000000', max_length=16, verbose_name='карта'),
        ),
    ]
