# Generated by Django 4.2.6 on 2023-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payments_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card',
            field=models.CharField(default='4142424242424242', max_length=16, verbose_name='карта'),
        ),
    ]
