# Generated by Django 4.2.6 on 2023-10-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_well'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Well',
            new_name='Course',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
