# Generated by Django 4.2.6 on 2023-10-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_course_active_lesson_active_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(verbose_name='сумма оплаты'),
        ),
    ]
