# Generated by Django 4.2.6 on 2023-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_course',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_lesson',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_course_lesson',
            field=models.CharField(choices=[('курс', 'курс'), ('урок ', 'урок ')], default='курс', max_length=50, verbose_name='платеж'),
        ),
    ]
